# Generated by Django 4.2.4 on 2023-08-31 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hastags',
            new_name='hashtags',
        ),
    ]
