# Generated by Django 4.2.4 on 2023-08-31 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_post_created_at_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_users',
            field=models.ManyToManyField(default=[], related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
