# Generated by Django 4.2.4 on 2023-09-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_liked_users_alter_post_likes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='liked_posts',
            field=models.ManyToManyField(default=[], related_name='liked', to='posts.post'),
        ),
    ]
