# Generated by Django 4.2.4 on 2023-09-04 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_age'),
        ('users', '0002_profile_liked_posts'),
    ]

    operations = [
    ]
